<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <div class="logo">
            <img src="" alt="logo">
        </div>

        <nav>
            <a 
                href=""><img src="" alt="home"></a>
            <a href="">GALERIE</a>
            <a href="">DEVENIR VIP</a>
            <a href="">SERVEUR</a>
        </nav>
    </header>

    <div class="tutos">
        <a href="">Tutoriels <img src="" alt=""> </a>
        <a href="">Event <img src="" alt=""> </a>
    </div>
    
</body>
</html>