
<div class="content">

    <?php 
        //content pour formulaires.php ********
        //foreach($data as $fEmployee){
        //     echo '<div class="prenom">';
        //     echo $fEmployee['prenom'].'<br>';
        //     echo '</div>';
        //     echo '<div class="contenu">';
        //     foreach($fEmployee as $key => $value){
        //     echo $key.' : '. $value. '<br>';  
        //     }
        //     echo '</div>';
        // }
        ?>
    


    <form method="post" action="index.php?action=traitement" enctype="multipart/form-data">
        <legend>Votre message :</legend>
        <div>
            <label for="pseudo">Pseudo</label>
            <input type="text" name="pseudo" id="pseudo" value="<?= $_POST['pseudo'] ?? ''; ?>">
        </div>
        <div>
            <label for="password" id="password">Mot de passe</label>
            <input type="password" id="password" name="password">
        </div>
        <div>
            <label for="picture" id="password">Photo</label>
            <input type="file" id="picture" name="picture">
        </div>
        <textarea name="description" id="description" cols="30" rows="10"></textarea>

        <button type="submit">Valider</button>
    </form>

</div>





<!-- <p>Bonjour <?php //echo $_SESSION['user']['pseudo'] ?? 'User'?></p>
        <a href="?action=deco" style='color:black'>Deconnexion </a> -->