
<div class="content">
    <?php if(isset($_SESSION['user'])) : ?>
    <div class="link-new-msg">
        <a href="index.php?action=formulaires1">Nouveau message</a>
    </div>

        <?php if(isset($_SESSION['user']['pseudo'])) : ?>
        <div class="connection">
        <?php echo $_SESSION['user']['pseudo']. ' <a href="?action=deconnection">Deconnexion</a><br>'; ?> 
        </div>
        <?php endif; ?>
    <?php endif; ?>

    <?php 
        //content pour formulaires.php ********
        //foreach($data as $fEmployee){
        //     echo '<div class="prenom">';
        //     echo $fEmployee['prenom'].'<br>';
        //     echo '</div>';
        //     echo '<div class="contenu">';
        //     foreach($fEmployee as $key => $value){
        //     echo $key.' : '. $value. '<br>';  
        //     }
        //     echo '</div>';
        // }
        ?>
    


    <form method="post" action="index.php?action=traitement" enctype="multipart/form-data">
        <legend>Votre message :</legend>
        <div>
            <label for="pseudo">Pseudo</label>
            <input type="text" name="pseudo" id="pseudo" value="<?= $_SESSION['user']['pseudo'] ?? ''; ?>">
            <p style="color:red;"><?=  $_SESSION['user']['errorPseudo']  ?? '' ?></p>
            <?php unset($_SESSION['user']['errorPseudo']); ?>

        </div>
        
        <?php if(!isset($_SESSION['user']['password'])) : ?>
        <div>
            <label for="password" id="password">Mot de passe</label>
            <input type="password" id="password" name="password">
            <p style="color:red;"><?=  $_SESSION['user']['errorPassw']  ?? '' ?></p>
            <?php unset($_SESSION['user']['errorPassw']); ?>
        </div>
        <?php endif; ?>

        <div>
            <label for="picture" id="picture">Photo</label>
            <input type="file" id="picture" name="picture">
        </div>
        <textarea name="description" id="description" cols="30" rows="10"></textarea>

        <button type="submit">Valider</button>
    </form>

</div>



